### ISSUE TITLE
.eslintignore file is ignored

### ISSUE THREAD

**Issue by tschoartschi** [jonathanKingston/ember-cli-eslint#13]
I have a script folder inside my ember cli project. I dont want to eslint this script folder because it is just quick&dirty try-out code of prototype-ideas. Now I put a .eslintignore file into my project root, right next to .eslintrc.

But the folder is still linted... what am I doing wrong?

Thanks

**Comment by tschoartschi** [comment]
@jonathanKingston don't worry. I'm happy that I can use ember-cli-eslint and if I know this is an issue it's ok. I'll wait until it is fixed :-) it is good to know that it is a bug so I don't need to spend more time trying to get it work.

**Comment by jonathanKingston** [comment]
@tschoartschi the latest ember-cli-eslint@latest should solve this (I'm holding off making this a full 1.0.0 release until certain all issues are over)

**Comment by ezpuzz** [comment]
`"latest"` doesn't seem to include index.js and there is a big tmp folder that comes with it?
actually the stable version from npm also seems to include a big `tmp` folder that I don't think should be there.

**Comment by jonathanKingston** [comment]
Always seems to happen with index.js files being missed there is an npm issue for it. tmp is my fault which should now be resolved.

**Comment by jonathanKingston** [comment]
Does `npm install ember-cli-eslint@latest` work for you both for this issue? @ezpuzz and @tschoartschi

**Comment by ezpuzz** [comment]
beta.9 with my .eslintignore containing 
```
**/modules/**
```
works to not lint imported addons.  Without it in place the modules do get linted.
beta.10 is missing index.js again.

haven't tried the .eslintignore for any other purpose though.

**Comment by jonathanKingston** [comment]
I think I'm getting close to finding out what is causing that index.js issue with npm, it's an outstanding issue that has not been fixed but seems to hit me more than anyone else (which points at it being a memory issue probably).

Yeah so I think that it is fair to say we now have .eslintignore files being read fine the other issue covers the addon usage error.

**Comment by mmahalwy** [comment]
@jonathanKingston any luck with this? I am facing the same problem too

**Comment by mmahalwy** [comment]
Hmm actually when I am using the @latest, the ignore works but now it's not running the linter against my files in `app/**`

How come!

**Comment by mmahalwy** [comment]
Okay, discovered what I was doing wrong and that is this in my ignore
`**/*.tmp/`
The reason was, I didn't understand why the eslint was running the files in the tmp folder vs how master is doing it, against the files themselves...

**Comment by jonathanKingston** [comment]
Sorry I'm away at the moment so not able to answer many mails.

It has been on my todo list to move where the code is linting, it was the only way I could get it to work quickly.

However yeah please use latest, once I fix this issue then we should be ok to bump to version 1.

Thanks

**Comment by mmahalwy** [comment]
Awesome! Thanks @jonathanKingston

**Comment by tschoartschi** [comment]
@jonathanKingston I did a restructure of my project directory structure so I don't need the .eslintignore anymore. Because you wrote that you would bump the version to 1, maybe this issue is also interesting for you https://github.com/adametry/gulp-eslint/issues/72#issuecomment-121655287 (I'm not sure if it is really worth to open a new issue on this)

**Comment by jonathanKingston** [comment]
@tschoartschi latest version now published thanks for the heads up. Back home now so will likely work on this soon.

**Comment by ezpuzz** [comment]
my builds are breaking again, the .eslintignore is not being applied to the imported modules

eg.
```
modules/ember-rapid-forms/utils/utils.js
  2:4  error  Utils is defined but never used   no-unused-vars
  5:8  error  Use ‘===’ to compare with ‘null’  no-eq-null

✖ 2 problems (2 errors, 0 warnings)
```

before the output was `tmp/modules/whatever` but now the tmp is gone again?  I'm on 0.2.5 for this.

**Comment by jonathanKingston** [comment]
Try the beta again? `1.0.0-beta.14`

**Comment by tschoartschi** [comment]
I installed version ```1.0.0``` today and now my tmp folder is linted again

So I get linting errors for example this file:
```
/../../tmp/funnel-output_path-Mm8daVKN.tmp/routes/application.js
```
My eslintignore file looks as follows:

```
tmp/
dist/
```

It was fine until I upgraded. What could be the issue?

**Comment by yagni** [comment]
@tschoartschi Check your glob syntax. I struggled with this for a bit and found out that was my problem. For example, instead of tmp/, try **/tmp/**

**Comment by BrianSipple** [comment]
Should be fixed by https://github.com/jonathanKingston/broccoli-lint-eslint/pull/30

**Comment by v-shan** [comment]
Hi @BrianSipple can we get broccoli-lint-eslint bumped to get that change in?

**Comment by alexlafroscia** [comment]
I think the `.eslintignore` issues might be more complex than that; see #82

**Comment by rwwagner90** [comment]
Is this still an issue? I am trying to exclude `tests/helpers/*.js` in a `.eslintignore` file and it does not ignore the files.

**Comment by alexlafroscia** [comment]
Yup, definitely still an issue.  See #82
