### ISSUE TITLE
Make eslint tests run in ember test --server 

### ISSUE THREAD

**Issue by chrisgame** [jonathanKingston/ember-cli-eslint#16]
Is it possible to make test'em run eslint the way it currently runs jshint? And ideally not run jshint?

**Comment by jonathanKingston** [comment]
Works for me, do you have the latest version of the .eslintrc file?

**Comment by chrisgame** [comment]
Perhaps not will check tomorrow and get back to you. Thanks for the fast
response!

**Comment by jonathanKingston** [comment]
I had an issue with:
```
"rules": [
```
Should have been:
```
"rules": {
```

Tired coding does this to me.

Anyway there is some issues with the package I am ironing out before we hit 1.0.0 so certainly willing to wait until this is resolved too.

**Comment by chrisgame** [comment]
The .eslintrc file looks okay.
I'm only running version 0.2.4 do i need to be on the beta?

**Comment by chrisgame** [comment]
Also just to clarify i get the output correctly when building or starting to run the tests...

![image](https://cloud.githubusercontent.com/assets/766429/7743666/e2ec0d6c-ff94-11e4-8a5b-0962eb67a85c.png)

But as you can see it doesn't actually fail in the in the testem runner. It reports all 241 tests passed.

**Comment by jonathanKingston** [comment]
@chrisgame worth trying the beta as I say, it is basically working fine.

```
npm install ember-cli-eslint@latest; ember generate ember-cli-eslint;
```

Then for the output are you using the `testGenerator`?

**Comment by chrisgame** [comment]
@jonathanKingston Yep, i've followed the instructions in the read me. 

With the beta version i get the following...
![image](https://cloud.githubusercontent.com/assets/766429/7773299/88b39cae-009b-11e5-9d1a-e0104f7168ef.png)

I've pushed up and clean ember cli app with only the addon installed and the steps taken on the readme so you can see if i'm doing anything stupid. You can find it here 
https://github.com/chrisgame/clean-install-ember-cli-eslint

**Comment by jonathanKingston** [comment]
@chrisgame looks like you need to run:
```
npm install --save-dev eslint-config-ember
```

I will add this to a common issues section in the README; the .eslintrc points to it which you can totally get rid of if you choose but hopefully are pretty sane defaults (Which I am open to hearing feedback on too here: https://github.com/jonathanKingston/eslint-config-ember).

**Comment by chrisgame** [comment]
@jonathanKingston :blush: I get it now! Works like a dream, thanks for your help.
