### ISSUE TITLE
ember install ember-cli-eslint fails

### ISSUE THREAD

**Issue by ismay** [jonathanKingston/ember-cli-eslint#17]
When trying to install ember-cli-eslint with:

```bash
ember install ember-cli-eslint
```

The install fails with:
```bash
Install failed. Could not find addon with name: ember-cli-eslint
```

an `npm install` of `ember-cli-eslint` does work however. And after that the `ember install` works as well (and generates the eslintrc files in root and tests). I don't know if that's the intended behaviour, but I couldn't find it in the readme.

**Comment by jonathanKingston** [comment]
I'm fairly certain this was an issue with Ember that has now gone away in the latest builds. Can you verify please (sorry for the delayed responses here)?

**Comment by ismay** [comment]
Np, verified it and it seems to work for me now (with `ember-cli: ^1.13.1`).

**Comment by jonathanKingston** [comment]
Cool thanks!
