### ISSUE TITLE
ember build fails because of out of date dependencies

### ISSUE THREAD

**Issue by kevintechie** [jonathanKingston/ember-cli-eslint#20]
The version of eslint referenced by the broccoli-lint-eslint dependency is out of date and doesn't support the .eslintrc settings of the dependent eslint-config-nightmare-mode package. Updating to the latest broccoli-lint-eslint should fix the problem.

**Comment by baron1405** [comment]
Hi, I am relatively new to ember and its ecosystem. How and where do I update the broccoli-lint-eslint version. I am awash in *.json configuration files :-) I have identified that with ember-cli 1.13.6, I get an Illegal import declaration error during a build if I ember install ember-clint-eslint and there is no error when I do not install it.

Thanks for your help.

**Comment by jonathanKingston** [comment]
Pretty sure this has now been resolved sorry for the delay.
