### ISSUE TITLE
dated `eslint-config-ember` installed

### ISSUE THREAD

**Issue by kangkyu** [jonathanKingston/ember-cli-eslint#25]
Following seen after `ember install ember-cli-eslint` by instruction
```
    "eslint-config-ember": "0.0.5"
```
Related to https://github.com/jonathanKingston/eslint-config-nightmare-mode/issues/1 it worked as desired after `npm install --save-dev eslint-config-ember` updating. It became
```
    "eslint-config-ember": "^0.2.0"
```
I think it would look better if it's done after `ember install ember-cli-eslint` itself. Thank you for nice ember eslint dependency by the way.

**Comment by BrianSipple** [comment]
+1

Same issue -- and same success with the fix mentioned by @kangkyu.

**Comment by jonathanKingston** [comment]
The blueprint was out of date due to the dependency breaking. I think we should go ahead and fix that so there is still one step only and mop up the mess if there is any. (After all worst case scenario it's too strict or out of date config).
