### ISSUE TITLE
Unexpected token issue

### ISSUE THREAD

**Issue by ssirowy** [jonathanKingston/ember-cli-eslint#36]
Our testing framework started breaking with this message today from `ember-cli-eslint`.  Was anything pushed to `1.2.1` that is causing this?

<img width="853" alt="screen shot 2016-03-09 at 3 52 10 pm" src="https://cloud.githubusercontent.com/assets/191263/13654762/0bdcf1ee-e60f-11e5-84a9-6eb83a2a6445.png">

**Comment by jonathanKingston** [comment]
See @chriskrycho's fixes: https://github.com/jonathanKingston/broccoli-lint-eslint/pull/19 Same happened there.

**Comment by ssirowy** [comment]
Ok thanks.  Will this package be updated to point to new work soon?

**Comment by chriskrycho** [comment]
I won't have time during the week—I've already spent a fair bit of time on open source stuff the last few weeks—so if @jonathanKingston doesn't have time, it'll be the weekend. That said, if it's still sitting, I will put together a PR to fix it this weekend. @ssirowy, the changes are pretty straightforward, though, if you want to tackle them yourself. If not, like I said: probably Saturday.

**Comment by BrianSipple** [comment]
Seems closable after https://github.com/jonathanKingston/broccoli-lint-eslint/pull/19 was merged.
