### ISSUE TITLE
Other maintainer wanted

### ISSUE THREAD

**Issue by jonathanKingston** [jonathanKingston/ember-cli-eslint#37]
I haven't used Ember for the last 8 or so months, which means that I'm taking a lot of my free time to manage changes on projects like this.

I would like a keen maintainer who can work in times when I am busy.

Apply here.

**Comment by rwjblue** [comment]
Happy to take over.

**Comment by jonathanKingston** [comment]
Added you as collaborator to both broccoli addon and ember-cli-eslint. Feel free to pull me into any conversations etc... I still very much care about these projects so sad they are getting rusty.

**Comment by rwjblue** [comment]
Sounds good.  Can you also add me to NPM for them?

Also, these packages are super important to my testing RFC (where I am proposing using async/await which is not supported by JSHint)...

**Comment by jonathanKingston** [comment]
Added thanks so much. You have way too many projects on the go haha.

Looks interesting certainly, AVA is also a nice `async/await` testing lib which might slot in there. Pretty sure those changes will make Ember a crazy amount easier to test with anyway.

**Comment by rwjblue** [comment]
Confirm, that is exactly the idea.  Will check out AVA.

**Comment by BrianSipple** [comment]
To echo @rwjblue, I'd be happy to help out in any manner as well. 

I've been playing around with locally with both `ember-cli-eslint` and `eslint-config-ember` to try and get and get dependencies up to date and [address](https://github.com/jonathanKingston/eslint-config-ember/issues/6) [current issues](https://github.com/jonathanKingston/ember-cli-eslint/issues/38). I'd love to keep contributing going forward.

**Comment by alexlafroscia** [comment]
I know others have volunteered, but I would love to help out too!

**Comment by jonathanKingston** [comment]
Will add @BrianSipple based on his hard work which probably makes enough contributors for now.
Thanks all.
