### ISSUE TITLE
Version bump in broccoli-lint-eslint breaking apps

### ISSUE THREAD

**Issue by Patsy-issa** [jonathanKingston/ember-cli-eslint#38]
There's a currently know problem https://github.com/eslint/eslint/issues/5476 bumping the eslint version to 2.3.0 is breaking our apps that use babel-eslint as a parser, I tried to fork these repos and fix the version to 2.2.0 while a fix is published but I failed miserably. Any pointers would be much appreciated.

**Comment by chriskrycho** [comment]
@Patsy-issa, where are you getting stuck on the fork and fix?

**Comment by Patsy-issa** [comment]
@chriskrycho all good, going to go ahead and close this issue.
