### ISSUE TITLE
Cascading of eslint configs does not work

### ISSUE THREAD

**Issue by dschmidt** [jonathanKingston/ember-cli-eslint#4]
Hi,

according to the eslint documentation it is possible to cascade config files:
See "Configuration Cascading and Hierarchy" here http://eslint.org/docs/user-guide/configuring 

This does not seem to work with ember-cli-eslint or at least I could not make it work :-)

Best regards,
Dominik

**Comment by jonathanKingston** [comment]
As mentioned in #6:

>However #4 again is mostly out of my control as ESLint command line interface permits only one config and also doesn't sniff for the files. I believe this is the same as JSHint anyway.

[ESLint CLI](http://eslint.org/docs/user-guide/command-line-interface) is the interface used and doesn't permit the cascade. I would suggest the feature should come from their library if there is a desire for it.
I'm not really sure it would make sense to retrofit that on top of the functionality here, especially as I fear it would impact build speed significantly.

I have an interest in supporting this however I would prefer it to be native and also be able to be turned off via a cli argument.

Thanks

**Comment by topaxi** [comment]
I'm not so sure about this, I don't have time to go more into it but I was using gulp-eslint which does exactly this.

I think this is the relevant line in gulp-eslint:
https://github.com/adametry/gulp-eslint/blob/master/index.js#L19

Eslint Documentation:
http://eslint.org/docs/developer-guide/nodejs-api.html#getconfigforfile()

**Comment by jonathanKingston** [comment]
@topaxi yup I stand corrected, I was reading with tired eyes.

I'll get on this as as you mention will likely solve the testing issue too.

**Comment by jonathanKingston** [comment]
@dschmidt and @topaxi if you get chance, the branch here 'relative-tests' should solve this issue and many of the others. Not publishing yet as I haven't had enough time to test it.
I will publish this tomorrow along with clearing out all the other issues.

**Comment by jonathanKingston** [comment]
This is now released, let me know if you have any issues.

**Comment by dschmidt** [comment]
Seems to work fine and even restarting ember-cli to reload the config isn't neccessary anymore (at least I believe it was before)! Cool, thanks!

**Comment by jonathanKingston** [comment]
@dschmidt :+1: thanks for testing.

**Comment by dschmidt** [comment]
I did observe the config changing behaviour some more: it seems the config is read on every build now, but new builds still need to be triggered by changing a source file. When you change a rule to allow a certain thing in your source file, it would be much handier to trigger a new build when just the config changes ... should I file a ticket for that or doesn't seem to make enough sense? ;-)

**Comment by jonathanKingston** [comment]
So I think your use case you are asking for is:

- Edit .eslintrc file
- Application gets rebuilt and tested with new config

I'm fairly certain that wouldn't have worked in the previous setup either.

If that is correct, please create a new issue as it isn't related to this (other than the possibility it was monitored before).
