### ISSUE TITLE
Ignored files fail `ember test`

### ISSUE THREAD

**Issue by alexlafroscia** [jonathanKingston/ember-cli-eslint#44]
I have some files that I want to ignore, and have ignored them using an `.eslintrc` file.  However, the fact that they are ignored raises an error, which then fails the `ember test` run.  Would it be possible to prevent these warning from failing the build?  I feel like, if the user has explicitly listed the files they want to ignore, then even these warnings should be ignored.

**Comment by BrianSipple** [comment]
Addressed with https://github.com/jonathanKingston/broccoli-lint-eslint/issues/30
