### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by jonathansamines** [jonathanKingston/ember-cli-eslint#45]
It seems like a lot of work has been done on this module since the last published version (1.2.1) quite time ago, is there any plans to publish a new version of this module?

**Comment by BrianSipple** [comment]
Absolutely!

We added a few collaborators to the project [recently](https://github.com/jonathanKingston/ember-cli-eslint/issues/37), and so I think what you're seeing at the moment is that it's still a bit nebulous as to who publishes versions and when. 

@jonathanKingston: I'd been meaning to get this clarified, as it looks like I'm able to draft new releases here on Github, but not publish new versions on npm. It feels like this might be a blocker for efficiently keeping everything up to date (although I'm not sure if the permissions are the same for @rwjblue).

In either case, I'm thinking of putting together a milestone for a new release that summarizes some of the recent changes made to both `ember-cli-eslint`, and to [`broccoli-lint-eslint`](https://github.com/jonathanKingston/broccoli-lint-eslint), which this project is [expecting to receive a few benefits from](https://github.com/jonathanKingston/broccoli-lint-eslint/pull/25). Stay tuned, @jonathansamines.

**Comment by jonathanKingston** [comment]
Hey, yeah added you now. Hopefully we can launch each new version with another maintainers consensus now that would be the only direction I would like to head in.

New milestone sounds great and there are other changes in the latest ESLint that keep cropping up so there will always be more work.

**Comment by BrianSipple** [comment]
https://github.com/jonathanKingston/ember-cli-eslint/releases/tag/v1.3.0 😄
