### ISSUE TITLE
git tags missing

### ISSUE THREAD

**Issue by Turbo87** [jonathanKingston/ember-cli-eslint#49]
According to NPM the current version of this project is `1.2.1` but the repo only shows `1.1.0` as the latest release. It would be a good idea to keep the tags here in sync with NPM releases.

**Comment by rwjblue** [comment]
Agreed

**Comment by Turbo87** [comment]
@rwjblue are there actually projects where you're not a "Collaborator"... 😂

**Comment by BrianSipple** [comment]
Tags for [1.2.0](https://github.com/jonathanKingston/ember-cli-eslint/releases/tag/1.2.0) and [1.2.1](https://github.com/jonathanKingston/ember-cli-eslint/releases/tag/1.2.1)

**Comment by just4fun** [comment]
@Turbo87 That issue seems like not the same.
@BrianSipple Could you take a look at npm about this package?

**Comment by Turbo87** [comment]
@just4fun I think it is related because the `1.2.1` tag seems to be attached to the wrong commit. I think d7e0c3281bdd4214d1a072fd8591ec4539861ee1 is probably the right target for that tag.

@BrianSipple we currently seem to have a mix of tag names, some with a `v` prefix and some without. it would probably be a good idea to adjust those to stay consistent.

**Comment by BrianSipple** [comment]
@Turbo87 👍  on the consistent tag names. I renamed tags without a `v` to make sure that they do have the prefix. 

Also, having npm find the right tag for `1.2.1` would definitely fix #52. My only confusion is whether or not that's possible. Updating the current tag for `1.2.1` to point to [d7e032](https://github.com/jonathanKingston/ember-cli-eslint/commit/d7e0c3281bdd4214d1a072fd8591ec4539861ee1) didn't seem to change the version that future `npm installs` were finding. 

Another short-term solution would be publishing `1.3.0` -- which I'm planning to do after updating  `broccoli-lint-eslint`. ([Getting `2.2.0` was the last blocker](https://github.com/jonathanKingston/ember-cli-eslint/milestones/1.3.0)). It doesn't help anyone using `1.2.1`, though, which, even though there's no reason not to jump to 1.3.0, still kind of miffs me .
