### ISSUE TITLE
Rename eslint.json to .eslintrc

### ISSUE THREAD

**Issue by topaxi** [jonathanKingston/ember-cli-eslint#5]
I'd prefer to use .eslintrc instead of eslint.json as executing eslint manually looks for .eslintrc (which is what my editor does on save).

**Comment by jonathanKingston** [comment]
:+1: .eslintrc mostly to match .jshintrc and localised copy convention (ESLint uses .json internally and manual suggests using json).

**Comment by jonathanKingston** [comment]
I'll implement this tomorrow, it should probably be configurable too.

**Comment by jonathanKingston** [comment]
Done and released thanks.
