### ISSUE TITLE
Add separate eslint config for tests

### ISSUE THREAD

**Issue by topaxi** [jonathanKingston/ember-cli-eslint#6]
Tests have different globals and helper functions, it would be handy if ember-cli-eslint would behave similar to default ember-cli jshint with a seperate eslint config as `tests/.eslintrc`

**Comment by topaxi** [comment]
This would probably work nicely together with #4

**Comment by jonathanKingston** [comment]
:+1: to changing to this and actually I was going to raise this tonight anyway after needing it today.

However #4 again is mostly out of my control as ESLint command line interface permits only one config and also doesn't sniff for the files. I believe this is the same as JSHint anyway.

**Comment by jonathanKingston** [comment]
@topaxi this should now work witht he ember-cli-eslint@latest yet to release 1.0.0 before all the issues are ironed out.

**Comment by jonathanKingston** [comment]
@topaxi closing as confirmed to be working with the latest beta build.
Thanks
