### ISSUE TITLE
Disable jshint

### ISSUE THREAD

**Issue by topaxi** [jonathanKingston/ember-cli-eslint#7]
Probably more a question, but after googling around without luck...
Is there a way to disable only the jshint tests?

```javascript
var app = EmberApp({
  'hinting': false
})
```

Seems to disable both, jshint and jslint.

Maybe this belongs more into ember-cli, I'm not sure.

**Comment by jonathanKingston** [comment]
@topaxi linting comes from both ember-cli-mocha/qunit currently so it might belong as a flag in ember-cli however would trickle down to those two. Either way there is a ticket raised on ember-cli-mocha:
https://github.com/switchfly/ember-cli-mocha/issues/44

It is mostly out of my control however you can turn jshint off with code comments: `/* jshint ignore: start */` however this is not brilliant.

I'm likely going to raise this as a formal RFC with ember-cli if there continues to be little notice as @teddyzeenny seems to be interested from past comments and his changes to Ember inspector: https://github.com/emberjs/ember-inspector/commit/b8f6226ed3ca20819e7beaa818c15eba0687c97d

**Comment by jonathanKingston** [comment]
@topaxi just chiming in with an update here so you are fully aware. I raised the following: https://github.com/ember-cli/rfcs/pull/15 which would be great if you could provide feedback on if you have any.

**Comment by mmahalwy** [comment]
@jonathanKingston any update on this?

**Comment by jonathanKingston** [comment]
@mmahalwy I think time is the limiting factor here sorry. I'm probably going to submit a patch to ember-cli soon so long as @stefanpenner is ok with that.

**Comment by yagni** [comment]
The next release of ember-cli-qunit will support the 'useLintTree' option (see [here](https://github.com/ember-cli/ember-cli-qunit/commit/6317f111a139d5d39d8a7703bd12cf013db8fd58) for relevant pull request) for disabling the JSHint test generation. When it's released, something like this should do the trick:
```javascript
var app = new EmberApp({
  "ember-cli-qunit": {
    useLintTree: false
  }
});
```

**Comment by mmahalwy** [comment]
@yagni any idea when it will be released?

**Comment by yagni** [comment]
@mmahalwy Unfortunately no, but it looks like they have a history of monthly releases, so I bet one is due any day now. I'll post here when I notice one.

**Comment by yagni** [comment]
Great news: a new version of ember-cli-qunit has been released and useLintTree works great! See the readme at https://github.com/ember-cli/ember-cli-qunit for an example of how to use it to disable JSHint. Should be able to close this one now.

**Comment by nybblr** [comment]
@jonathanKingston is this still in progress for ember-cli-mocha, or maybe I've missed the good tidings on another issue?

I'm using ember-cli-eslint + ember-cli-mocha; an (old) version of eslint is used during builds, but ember test continues to generate jshint tests.

**Comment by jonathanKingston** [comment]
So the good news is all the test libraries were fixed to turn this off if you set this setting:
https://github.com/switchfly/ember-cli-mocha#turning-off-jshint-linting

I think there was some mention by @topaxi to set this to false if a addon like ember-cli-eslint has it's own linting, however I don't know if that went any further than discussion.

**Comment by nybblr** [comment]
Gotcha, I'm using that setting currently but it turns off *all* linting in the test suite, including eslint. Was hoping I could have eslint run in the test suite with Mocha =)

**Comment by jonathanKingston** [comment]
@nybblr I have not tested it extensively however it should work with Mocha as that was my old setup I was using regular.
Are you mixing this up with the general turn off linting flag?

**Comment by nybblr** [comment]
@jonathanKingston Hmm, maybe I am? Here's my setup:

```javascript
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    sassOptions: {
      includePaths: [
        'bower_components'
      ]
    },
    babel: {
      includePolyfill: true
    },
    'ember-cli-mocha': {
      useLintTree: false
    }
  });

  return app.toTree();
};
```

My `package.json` has:

```json
    "ember-cli-mocha": "^0.10.0",
    "ember-cli-eslint": "1.2.1",
```

The `useLintTree` seems to turn off all linting, but removing that flag still runs JSHint specs in `ember test`. Anything obvious?

**Comment by jonathanKingston** [comment]
@nybblr nothing obvious sorry, can you raise another bug with ember-cli-mocha and reference this and me?
